import { CardH } from "./card-h";
export const CARDH : CardH[]=[
  {id:0,
    src:"",
    alt:"",
    href: "#",
    classR:"cardH",
    nameE:"tu vieja",
    exp:"zzz",
    },
    {id:1,
      src:"",
      alt:"",
      href: "#",
      classR:"cardH",
      nameE:"tu vieja",
      exp:"zzz",
      },
      {id:1,
        src:"",
        alt:"",
        href: "#",
        classR:"cardH",
        nameE:"tu vieja",
        exp:"zzz",
        },
        {id:1,
          src:"",
          alt:"",
          href: "#",
          classR:"cardH",
          nameE:"tu vieja",
          exp:"zzz",
          },
          {id:1,
            src:"",
            alt:"",
            href: "#",
            classR:"cardH",
            nameE:"tu vieja",
            exp:"zzz",
            },
]
