import { Proyecto } from "./proyectos"

export const PROYECTO:Proyecto[]=[
  {id:0,
    src:"",
    alt:"",
    href: "#",
    classR:"cardH",
    nameE:"1",
    exp:"zzz",
    },
    {id:1,
      src:"",
      alt:"",
      href: "#",
      classR:"cardH",
      nameE:"2",
      exp:"zzz",
      },
      {id:1,
        src:"",
        alt:"",
        href: "#",
        classR:"",
        nameE:"3",
        exp:"zzz",
        },
        {id:1,
          src:"",
          alt:"",
          href: "#",
          classR:"cardH",
          nameE:"4",
          exp:"zzz",
          },
          {id:1,
            src:"",
            alt:"",
            href: "#",
            classR:"cardH",
            nameE:"tu vieja",
            exp:"zzz",
            },
]
